#!/usr/bin/env python
from os.path import expanduser
import shutil
import sys

try:
  shutil.copy('./cheat', '/usr/local/bin/')
  shutil.copytree('./.cheat', expanduser('~') + '/.cheat')
except IOError as e:
   print >> sys.stderr, "This installer must be run as root."
   sys.exit(1)
